[package]
name = "snake-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
itertools = "0.13.0"
rand = "0.8.5"
ratatui = "0.27.0"
rayon = "1.10.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
serde_json_path_to_error = "0.1.4"
